install:
	install -d $(DESTDIR)/etc/qubes-rpc
	install -d $(DESTDIR)/etc/qubes-rpc/policy
	install -m 0644 qubes.Dom0Shell $(DESTDIR)/etc/qubes-rpc/qubes.Dom0Shell
	install -m 0644 policy/qubes.Dom0Shell $(DESTDIR)/etc/qubes-rpc/policy/qubes.Dom0Shell
